# MQTT 配置
mqtt:
  enabled: true
  offline-cache:
    max-queue-size: 10000
    dedup-expire-minutes: 5
    replay-delay-ms: 100

jwt:
  secret: "789&kLp23$87bnM90!789poI87&90lkJ78*90jhG78!90fdS78%90saD78^90xcV78&90zbN78!这是安全密钥1234567890"
  expiration: 86400000

# Spring 核心配置：允许 Bean 定义覆盖（解决 Bean 重复定义冲突）
spring:
  main:
    allow-bean-definition-overriding: true  # 缩进在 spring 下，作为子配置
  # 数据库配置
  datasource:
      url: jdbc:mysql://120.46.151.248:3306/campus_water_management?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: member
      password: Hdp11008@
      driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    # Redis 配置
    data:
      redis:
        host: 127.0.0.1
        port: 6379
        password:
        database: 0
        timeout: 3000ms
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: -1ms

# 服务器编码配置
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8081
  ssl:
      key-store: classpath:keystore.p12
      key-store-password: 123456
      key-store-type: PKCS12
      key-alias: myhttps
  additional-ports:
    - port: 8080
      protocol: HTTP